### ISSUE TITLE
How do I get xml format for PubReader

### ISSUE THREAD

**Issue by cweiming** [ncbi/PubReader#4]
Hi developer,

Thanks for providing this nice tool. But it doesn't seem to support the xml file downloaded from PMC.
How should I do? 

--
WM

**Comment by kolotev** [comment]
PubReader was not designed to work XML downloaded from PMC.
It works with HTML content generated based on XML from PMC.
You can check test folder for examples of HTML files from XML in the same folder.

**Comment by cweiming** [comment]
Hi kolotev,

I have checked XML format from test and XML format downloaded from PMC. Both formats are a little bit different. I generated HTML based on XML in test folder and presented on PubReader as well. But it didn't work HTML content generated based on XML downloaded from PMC.

`PubReader was not designed to work XML downloaded from PMC.
It works with HTML content generated based on XML from PMC.`

I am quite confused both. Is there any way to get the quailed XML file from PMC to generate HTML content so as to present on PubReader.

--
WM

**Comment by kolotev** [comment]
> I am quite confused both.

could you collaborate on your confusion? I can not help if I do not understand that.


> Is there any way to get the quailed XML file from PMC to generate HTML content so as to present on PubReader?

Technically you do not need PMC XML for that. PubReader was created to work with HTML content  (examples you can check in test folder).

You may need to come up with your own way to transform PMC XML articles (or articles from other sources) into HTML suitable for PubReader. PMC does not mandate the source XML format. Currently, PMC does not distribute the code which creates a  suitable HTML from PMC XML.

Sorry, if my comments give you little help.

**Comment by cweiming** [comment]
Hi kolotev,

Thanks for your answer.

I thought that XML in test folder comes from PMC so that the script of make-test-pages.sh is able to transform XML into HTML suitable for PubReader.

No more question.

I will try to find a way to make PMC XML format similar to your XML format and create HTML make-test-pages.sh to present on PubReader 

No more question.

Thanks!

--
WM
